### ISSUE TITLE
Error in "Browse" tab

### ISSUE THREAD

**Issue by jfcolom** [nicolasbrailo/VlcFreemote#2]
First of all, thank you for bringing this interesting functionality to F-Droid users. I am an old user of [Remote for VLC](https://code.google.com/archive/p/android-vlc-remote/) which was moved to archive repository long time ago, maybe because of its security problems.

Just after installing VlcFreemote, I was able to connect to my VLC HTTP service and play some file in the current play list. The issue came when I tried to explore the "Browse" tab in order to search for other sound files: I got a long error message telling something like "a bug related to ~ directory" during a few seconds and the app stopped. Unfortunately, the app keeps stopping again and again when I try to start it up (also after restarting the smartphone), so I cannot repeat the error and properly read the exact error message.

NOTE: I can browse files in my VLC HTTP service using the aforementioned old "Remote for VLC"

**Comment by jfcolom** [comment]
Yes!, this was the error message.

Sure, I would help you. However, I don't have Windows either, but a Linux system running VLC as a service with an invalid HOME folder.

I have VLC running on a Raspberry Pi with Linux (Voidlinux distro). Following the scripts of the init system, VLC is run this way by the root user:

```
exec chpst -u vlc:audio cvlc -I http --http-password **********
```

``chpst -u vlc:audio`` changes the owner of the vlc process to user "vlc" group "audio", but it is not changing $HOME or '~'. The home of the process remains ``/root``

Solution:

```
export HOME=/srv/www/vlc
exec chpst -u vlc:audio cvlc -I http --http-password **********
```

"Browse" tab VlcFreemote is working now! 

Thankyou very much!

**Comment by nicolasbrailo** [comment]
So I forgot to consider users with invalid $home. That's embarrassing, thanks for reporting!

Stackoverflow says '/' is somewhat more compatible, so in the next few days I'll release a new version defaulting to '/' instead of '~'. Maybe add an option to manually enter a path, if I have enough time. I'll also try to make error messages stay longer on the screen.

In the meantime: the app shouldn't crash with this error, it should simply disconnect from the server (or at least that's what it does in my two test devices). If you ever encounter a crash again, and copying the crashlog isn't too much work, I'd love to have a copy of `adb logcat`.

Thanks again for the bug report!

**Comment by jfcolom** [comment]
I don't see the stacktrace, but now I've found more info (the previous is not relevant):

```
09-03 18:22:50.972 27614 27614 E         : Couldn't `cd /home/student/mirror`. Will `cd ~` instead.
09-03 18:22:51.010 27614 27614 E         : Couldn't `cd ~`. Will `cd ~` instead.
09-03 18:22:51.010 27614 27614 E MainActivity: Programmer error! com.nicolasbrailo.vlcfreemote.model.VlcPath$VlcPath_ApplicationError: Fatal error: the default VlcPath (~) is not valid on your setup. Please submit a bug report.
```
